export default {
  GET_CART: 'GET_CART',

  GET_CART_REQUEST: 'GET_CART_REQUEST',
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_FAIL: 'GET_CART_FAIL',

  ADD_LOCAL_CART: 'ADD_LOCAL_CART',
  
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL',

  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART'
}