export default {
  GET_ITEMS: 'GET_ITEMS',

  GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_FAIL: 'GET_ITEMS_FAIL',

  SEARCH_ITEMS: 'SEARCH_ITEMS',
  SEARCH_ITEMS_REQUEST: 'SEARCH_ITEMS_REQUEST',
  SEARCH_ITEMS_SUCCESS: 'SEARCH_ITEMS_REQUEST',
  SEARCH_ITEMS_FAIL: 'SEARCH_ITEMS_REQUEST',
}